// Column headers for the Excel import, matching the importer's recognized
// headers. Two templates: the system-generated core columns (A–V) and the full
// "bulk" set (all departments). Sl. No. is auto-generated and omitted.

export const SYSTEM_GENERATED_HEADERS: string[] = [
  "SO NO.",
  "EC No.",
  "EC Generated Date",
  "EC RCVD In OPERATIONS",
  "EC sent date in Production",
  "FILE NO.",
  "CLIENT CODE",
  "Client Type",
  "Party",
  "Nature of Supply",
  "INDUSTRY TYPE",
  "Representative",
  "Item",
  "PO NO.",
  "Customer PO Date",
  "Model No.",
  "IF PUMP (QTY)",
  "PUMP S.NO.",
  "ORIENTATION",
  "LIQUID/ APPLICATION",
  "VERSION",
];

export const BULK_HEADERS: string[] = [
  ...SYSTEM_GENERATED_HEADERS,
  "Payment Terms",
  "Freight Terms",
  "Packing Requirement",
  "PI No.",
  "PI Date",
  "PI Value",
  "Payment Status",
  "DRG. Status",
  "DRG SENT TO CLIENT Dt.",
  "DRG. Approval Date",
  "Target Dt. For Drg",
  "BOI",
  "Gear BOX",
  "GB STATUS",
  "Motor",
  "MOTOR STATUS",
  "PENDING PARTS / BOI Others",
  "BOI DATE RECEIPT DATE",
  "Target Dt. For Purchase",
  "Required QC Documents",
  "Target Dt. For Doc. Submission",
  "Actual Dt. Of Doc. Submission",
  "LD (Yes)",
  "LD Date",
  "DISP. TARGET DT.",
  "Revise Disp. Target Dt",
  "Documents Required from Planning",
  "Pump Readiness Remarks",
  "Actual PUMP STATUS",
  "ASSEMBLED/ PACKED QTY",
  "Assembly date",
  "Readiness Dt. Rcvd from Planning",
  "Final Dt. for Packing & Dispatch",
  "Documents Required by Assembly/Dispatch Team",
  "Target Date for Dispatch Team",
  "ACTUAL Material Packing Date",
  "PLANNING STATUS",
  "Project",
  "Lot wise Packing slip remark",
  "Remarks/Status/Reason of Delay",
  "Master Reason of Delay",
  "DISPATCH STATUS",
  "LOT NO.",
  "Lot Wise Disp. Dt.",
  "Invoice Date",
  "Order Value",
];
