-- ===========================================================================
-- ECtoDispatch — database schema
-- Target: Azure Database for PostgreSQL (Flexible Server)
-- Apply with:  npm run db:migrate
-- ===========================================================================

-- Note: gen_random_uuid() is built into PostgreSQL core (v13+), which Azure
-- Flexible Server runs, so no pgcrypto extension is required.

-- ---------------------------------------------------------------------------
-- users
-- Roles and access status match the login / "Request Access" signup flow.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name     TEXT         NOT NULL,
    email         TEXT         NOT NULL,
    password_hash TEXT         NOT NULL,
    role          TEXT         NOT NULL
                               CHECK (role IN ('admin', 'central_visibility', 'operations',
                                               'accounts', 'drawing', 'planning', 'purchase',
                                               'qc', 'dispatch')),
    status        TEXT         NOT NULL DEFAULT 'pending'
                               CHECK (status IN ('pending', 'approved', 'rejected', 'disabled')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Case-insensitive unique email (so Jane@x.com == jane@x.com).
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key
    ON users (lower(email));

-- Bring existing tables up to date with the CHECK constraints above.
-- Drop the old role check first, migrate the legacy 'assembly' role to the new
-- 'dispatch' role, then apply the expanded role set.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
UPDATE users SET role = 'dispatch' WHERE role = 'assembly';
ALTER TABLE users ADD  CONSTRAINT users_role_check
    CHECK (role IN ('admin', 'central_visibility', 'operations', 'accounts',
                    'drawing', 'planning', 'purchase', 'qc', 'dispatch'));
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_status_check;
ALTER TABLE users ADD  CONSTRAINT users_status_check
    CHECK (status IN ('pending', 'approved', 'rejected', 'disabled'));

-- Keep updated_at current on every UPDATE.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- audit_log — activity trail: who signed in, when, and what they did.
-- Actor identity is denormalized so entries survive user deletion and so
-- failed logins (no user row) can still be recorded.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES users(id) ON DELETE SET NULL,
    user_email  TEXT,
    user_role   TEXT,
    action      TEXT NOT NULL,   -- e.g. login, order.create, access.approve
    category    TEXT NOT NULL,   -- auth | activity | ownership
    target      TEXT,            -- what was affected (SO/EC, user email, …)
    details     TEXT,            -- human-readable summary
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_log_created_at_idx ON audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS audit_log_category_idx ON audit_log (category);
CREATE INDEX IF NOT EXISTS audit_log_user_idx ON audit_log (user_id);

-- ===========================================================================
-- Order-to-Dispatch master tracker (normalized)
--
-- A core `orders` row, one detail table per department (1:1 via order_id),
-- and child tables for pumps and lots (1:many). Every detail/child table
-- references orders(id) ON DELETE CASCADE. Column letters map to
-- assets/excelData.xlsx. Free-form/status fields are TEXT so messy imports
-- don't fail; clear dates/money/qty use proper types for sorting and totals.
-- ===========================================================================

-- Core identity — cols A–V (client/agent kept as plain text for now),
-- plus BH Project and BP Order Value.
CREATE TABLE IF NOT EXISTS orders (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sl_no                    BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- A  Sl. No.
    so_no                    TEXT,           -- B  SO NO.
    ec_no                    TEXT,           -- C  EC No.
    ec_generated_date        DATE,           -- D  EC Generated Date
    ec_rcvd_operations_date  DATE,           -- E  EC RCVD In OPERATIONS
    ec_sent_production_date  DATE,           -- F  EC sent date in Production
    file_no                  TEXT,           -- G  FILE NO.
    client_code              TEXT,           -- H  CLIENT CODE
    client_type              TEXT,           -- I  Client Type
    party                    TEXT,           -- J  Party
    nature_of_supply         TEXT,           -- K  Nature of Supply
    industry_type            TEXT,           -- L  INDUSTRY TYPE
    agent                    TEXT,           -- M  AGENT
    item                     TEXT,           -- N  Item
    po_no                    TEXT,           -- O  PO NO.
    customer_po_date         DATE,           -- P  Customer PO Date
    model_no                 TEXT,           -- Q  Model No.
    pump_qty                 INTEGER,        -- R  IF PUMP (QTY)
    pump_sno                 TEXT,           -- S  PUMP S.NO.
    orientation              TEXT,           -- T  ORIENTATION
    liquid_application       TEXT,           -- U  LIQUID/ APPLICATION
    version                  TEXT,           -- V  VERSION
    project                  TEXT,           -- BH Project
    payment_terms            TEXT,           -- W  Payment Terms (Central Visibility-owned)
    master_reason_of_delay   TEXT,           -- BK Master Reason of Delay (order-level)
    dispatch_target_date     DATE,           -- AU DISP. TARGET DT. (set after payment confirmation)
    dispatch_target_revised_date DATE,       -- AV Revise Disp. Target Dt (when LD)
    drg_target_date          DATE,           -- AG Target Dt. For Drg (Central Visibility-owned)
    order_value              NUMERIC(14,2),  -- BP Order Value
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS orders_so_no_idx ON orders (so_no);
-- ec_no is temporarily dropped from orders (see the trim below), so this
-- index can only be (re)created while the column exists.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'orders' AND column_name = 'ec_no'
    ) THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS orders_ec_no_idx ON orders (ec_no)';
    END IF;
END $$;

-- Billing & Operations / PI — cols W–AB.
CREATE TABLE IF NOT EXISTS order_billing (
    order_id             UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    freight_terms        TEXT,           -- X  Freight Terms
    packing_requirement  TEXT,           -- Y  Packing Requirement
    pi_no                TEXT,           -- Z  PI No.
    pi_date              DATE,           -- AA PI Date
    pi_value             NUMERIC(14,2),  -- AB PI Value
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Accounts — col AC + the Payment Confirmed gate.
-- payment_status carries the gate value (Pending / Received / Confirmed / Hold);
-- 'Hold' means not confirmed → escalated to Central Visibility.
CREATE TABLE IF NOT EXISTS order_accounts (
    order_id                UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    payment_status          TEXT,        -- AC Payment Status (gate value)
    payment_confirmed_date  DATE,        -- set when payment is Confirmed
    hold_reason             TEXT,        -- escalation note when on Hold
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add the gate columns to any pre-existing order_accounts table.
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS payment_confirmed_date DATE;
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS hold_reason TEXT;

-- Drawing — cols AD–AG ("in case of Pump").
CREATE TABLE IF NOT EXISTS order_drawing (
    order_id                 UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    drg_status               TEXT,       -- AD DRG. Status
    drg_sent_to_client_date  DATE,       -- AE DRG SENT TO CLIENT Dt.
    drg_approval_date        DATE,       -- AF DRG. Approval Date
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Purchase / BOI — cols AH–AO ("in case of Pump").
CREATE TABLE IF NOT EXISTS order_purchase (
    order_id              UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    boi                   TEXT,          -- AH BOI
    gear_box              TEXT,          -- AI Gear BOX
    gb_status             TEXT,          -- AJ GB STATUS
    motor                 TEXT,          -- AK Motor
    motor_status          TEXT,          -- AL MOTOR STATUS
    pending_parts         TEXT,          -- AM PENDING PARTS / BOI Others
    boi_receipt_date      DATE,          -- AN BOI DATE RECEIPT DATE
    remarks               TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- (order_purchase's flat fields are dropped in the BOI restructure below — the
-- old `remarks` ADD was removed so it doesn't resurrect that column.)

-- QC — cols AP–AS.
CREATE TABLE IF NOT EXISTS order_qc (
    order_id               UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    required_qc_documents  TEXT,         -- AP Required QC Documents
    qc_doc_target_date     DATE,         -- AQ Target Dt. For Doc. Submission
    qc_doc_actual_date     DATE,         -- AR Actual Dt. Of Doc. Submission
    remarks                TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE order_qc ADD COLUMN IF NOT EXISTS remarks TEXT;

-- QC document attachments (1:many). Filled by the QC role itself (unlike the
-- rest of the QC section, which Central Visibility fills); stored directly in
-- Postgres as bytea.
CREATE TABLE IF NOT EXISTS order_qc_documents (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id      UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    file_name     TEXT NOT NULL,
    mime_type     TEXT,
    file_size     INT,
    file_data     BYTEA NOT NULL,
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- order_qc_documents is rekeyed to item_id in the v2 restructure below, so this
-- order_id index only applies while the old column still exists.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_qc_documents' AND column_name = 'order_id'
    ) THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS order_qc_documents_order_id_idx ON order_qc_documents(order_id)';
    END IF;
END $$;

-- QC requirement documents (1:many). The reverse direction from
-- order_qc_documents: reference/requirement files Central Visibility uploads
-- for QC to work from (specs, standards, drawings), not QC's own output.
-- Central Visibility uploads/deletes; QC (+ Central) can view/download.
CREATE TABLE IF NOT EXISTS order_qc_requirement_documents (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id      UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    file_name     TEXT NOT NULL,
    mime_type     TEXT,
    file_size     INT,
    file_data     BYTEA NOT NULL,
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Rekeyed to item_id in the v2 restructure below (guard as above).
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_qc_requirement_documents' AND column_name = 'order_id'
    ) THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS order_qc_requirement_documents_order_id_idx ON order_qc_requirement_documents(order_id)';
    END IF;
END $$;

-- Planning — cols AT–AX, BB, BC, BG.
CREATE TABLE IF NOT EXISTS order_planning (
    order_id                      UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    ld                            TEXT,  -- LD (Yes/No), filled by Central Visibility
    ld_date                       DATE,  -- AT LD Date (filled by Central Visibility)
    purchase_target_date          DATE,  -- AO Target Dt. For Purchase (filled by Planning)
    planning_documents_required   TEXT,  -- AW Documents Required from Planning (Central Visibility)
    pump_readiness_remarks        TEXT,  -- AX Pump Readiness Remarks
    planning_readiness_date       DATE,  -- BB Readiness Dt. Rcvd from Planning
    final_packing_dispatch_date   DATE,  -- BC Final Dt. for Packing & Dispatch
    planning_status               TEXT,  -- BG PLANNING STATUS
    actual_pump_status            TEXT,  -- AY Actual PUMP STATUS (filled by Planning)
    assembled_packed_qty          TEXT,  -- AZ ASSEMBLED/ PACKED QTY (filled by Planning)
    assembly_date                 DATE,  -- BA Assembly date (filled by Planning)
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Assembly & Dispatch — cols BD–BF, BJ, BL.
CREATE TABLE IF NOT EXISTS order_assembly_dispatch (
    order_id                     UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    dispatch_documents_required  TEXT,  -- BD Documents Required by Assembly/Dispatch
    dispatch_team_target_date    DATE,  -- BE Target Date for Dispatch Team
    actual_packing_date          DATE,  -- BF ACTUAL Material Packing Date
    delay_remarks                TEXT,  -- BJ Remarks/Status/Reason of Delay
    dispatch_status              TEXT,  -- BL DISPATCH STATUS
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE order_assembly_dispatch DROP COLUMN IF EXISTS full_dispatch_date;

-- Payment Terms move to the order (filled by Central Visibility); Billing &
-- Operations and Accounts see it read-only. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_terms TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_billing'
           AND column_name = 'payment_terms'
    ) THEN
        UPDATE orders o
           SET payment_terms = COALESCE(o.payment_terms, b.payment_terms)
          FROM order_billing b
         WHERE b.order_id = o.id;
        ALTER TABLE order_billing DROP COLUMN payment_terms;
    END IF;
END $$;

-- Target Date for DRG moves to the order (filled by Central Visibility);
-- Drawing sees it read-only. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS drg_target_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_drawing' AND column_name = 'drg_target_date'
    ) THEN
        UPDATE orders o
           SET drg_target_date = COALESCE(o.drg_target_date, dr.drg_target_date)
          FROM order_drawing dr
         WHERE dr.order_id = o.id;
        ALTER TABLE order_drawing DROP COLUMN drg_target_date;
    END IF;
END $$;

-- Target Date for Purchase moves to Planning (filled by Planning); Purchase
-- sees it read-only. Idempotent.
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS purchase_target_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_purchase' AND column_name = 'purchase_target_date'
    ) THEN
        -- ensure a planning row exists for orders that carry a purchase target
        INSERT INTO order_planning (order_id)
            SELECT pu.order_id FROM order_purchase pu
             WHERE pu.purchase_target_date IS NOT NULL
               AND NOT EXISTS (
                 SELECT 1 FROM order_planning pl WHERE pl.order_id = pu.order_id
               );
        UPDATE order_planning pl
           SET purchase_target_date = pu.purchase_target_date
          FROM order_purchase pu
         WHERE pu.order_id = pl.order_id
           AND pu.purchase_target_date IS NOT NULL
           AND pl.purchase_target_date IS NULL;
        ALTER TABLE order_purchase DROP COLUMN purchase_target_date;
    END IF;
END $$;

-- LD is an order-level flag (orders.ld), not a QC attribute. Migrate any QC
-- ld_applicable values onto orders.ld, then drop the QC column. Idempotent.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_qc' AND column_name = 'ld_applicable'
    ) THEN
        UPDATE orders o
           SET ld = COALESCE(o.ld, qc.ld_applicable)
          FROM order_qc qc
         WHERE qc.order_id = o.id AND qc.ld_applicable IS NOT NULL;
        ALTER TABLE order_qc DROP COLUMN ld_applicable;
    END IF;
END $$;

-- LR no./date are no longer tracked.
ALTER TABLE order_lots DROP COLUMN IF EXISTS lr_no;
ALTER TABLE order_lots DROP COLUMN IF EXISTS lr_date;

-- Dispatch lots — cols BI, BM, BN, BO (1:many).
CREATE TABLE IF NOT EXISTS order_lots (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id             UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    lot_no               TEXT,          -- BM LOT NO.
    lot_dispatch_date    DATE,          -- BN Lot Wise Disp. Dt.
    packing_slip_remark  TEXT,          -- BI Lot wise Packing slip remark
    invoice_date         DATE,          -- BO Invoice Date
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Rekeyed to item_id in the v2 restructure below (guard as above).
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_lots' AND column_name = 'order_id'
    ) THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS order_lots_order_id_idx ON order_lots (order_id)';
    END IF;
END $$;

-- updated_at triggers for the core + 1:1 detail tables.
DROP TRIGGER IF EXISTS orders_set_updated_at ON orders;
CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_billing_set_updated_at ON order_billing;
CREATE TRIGGER order_billing_set_updated_at BEFORE UPDATE ON order_billing
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_accounts_set_updated_at ON order_accounts;
CREATE TRIGGER order_accounts_set_updated_at BEFORE UPDATE ON order_accounts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_drawing_set_updated_at ON order_drawing;
CREATE TRIGGER order_drawing_set_updated_at BEFORE UPDATE ON order_drawing
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_purchase_set_updated_at ON order_purchase;
CREATE TRIGGER order_purchase_set_updated_at BEFORE UPDATE ON order_purchase
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_qc_set_updated_at ON order_qc;
CREATE TRIGGER order_qc_set_updated_at BEFORE UPDATE ON order_qc
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_planning_set_updated_at ON order_planning;
CREATE TRIGGER order_planning_set_updated_at BEFORE UPDATE ON order_planning
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_assembly_dispatch_set_updated_at ON order_assembly_dispatch;
CREATE TRIGGER order_assembly_dispatch_set_updated_at BEFORE UPDATE ON order_assembly_dispatch
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Move master_reason_of_delay from order_assembly_dispatch to orders (now an
-- order-level field captured at creation). Idempotent: copies any existing
-- values across, then drops the old column if it still exists.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS master_reason_of_delay TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_assembly_dispatch'
           AND column_name = 'master_reason_of_delay'
    ) THEN
        UPDATE orders o
           SET master_reason_of_delay = ad.master_reason_of_delay
          FROM order_assembly_dispatch ad
         WHERE ad.order_id = o.id
           AND ad.master_reason_of_delay IS NOT NULL
           AND o.master_reason_of_delay IS NULL;
        ALTER TABLE order_assembly_dispatch DROP COLUMN master_reason_of_delay;
    END IF;
END $$;

-- Move pump serial onto the order itself (one PUMP S.NO. per order) and drop
-- the former order_pumps child table. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pump_sno TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
         WHERE table_name = 'order_pumps'
    ) THEN
        UPDATE orders o
           SET pump_sno = p.pump_sno
          FROM (
            SELECT DISTINCT ON (order_id) order_id, pump_sno
              FROM order_pumps
             ORDER BY order_id, created_at
          ) p
         WHERE p.order_id = o.id
           AND o.pump_sno IS NULL
           AND p.pump_sno IS NOT NULL;
        DROP TABLE order_pumps;
    END IF;
END $$;

-- Dispatch target dates move to the order (filled by Central Visibility after
-- payment confirmation); Planning sees them read-only. Add an order-level LD
-- flag that gates the revised date. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ld TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS dispatch_target_date DATE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS dispatch_target_revised_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_planning'
           AND column_name = 'dispatch_target_date'
    ) THEN
        UPDATE orders o
           SET dispatch_target_date =
                 COALESCE(o.dispatch_target_date, pl.dispatch_target_date),
               dispatch_target_revised_date =
                 COALESCE(o.dispatch_target_revised_date, pl.dispatch_target_revised_date)
          FROM order_planning pl
         WHERE pl.order_id = o.id;
        ALTER TABLE order_planning DROP COLUMN dispatch_target_date;
        ALTER TABLE order_planning DROP COLUMN dispatch_target_revised_date;
    END IF;
END $$;

-- LD moves from orders into order_planning (filled by Central Visibility,
-- visible to Planning). Idempotent. Only runs while order_planning is still
-- SO-keyed (has order_id); after the v2 restructure below rekeys it to item_id,
-- LD lives permanently on orders and this dance is skipped.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_planning' AND column_name = 'order_id'
    ) THEN
        ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS ld TEXT;
    END IF;
END $$;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'orders' AND column_name = 'ld'
    ) AND EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_planning' AND column_name = 'order_id'
    ) THEN
        INSERT INTO order_planning (order_id)
            SELECT o.id FROM orders o
             WHERE o.ld IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM order_planning pl WHERE pl.order_id = o.id);
        UPDATE order_planning pl
           SET ld = o.ld
          FROM orders o
         WHERE o.id = pl.order_id AND o.ld IS NOT NULL AND pl.ld IS NULL;
        ALTER TABLE orders DROP COLUMN ld;
    END IF;
END $$;

-- Actual pump status / assembled qty / assembly date move from Assembly &
-- Dispatch into Planning (filled by Planning). Idempotent.
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS actual_pump_status TEXT;
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS assembled_packed_qty TEXT;
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS assembly_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_assembly_dispatch'
           AND column_name = 'actual_pump_status'
    ) THEN
        INSERT INTO order_planning (order_id)
            SELECT ad.order_id FROM order_assembly_dispatch ad
             WHERE (ad.actual_pump_status IS NOT NULL
                    OR ad.assembled_packed_qty IS NOT NULL
                    OR ad.assembly_date IS NOT NULL)
               AND NOT EXISTS (SELECT 1 FROM order_planning pl WHERE pl.order_id = ad.order_id);
        UPDATE order_planning pl
           SET actual_pump_status = COALESCE(pl.actual_pump_status, ad.actual_pump_status),
               assembled_packed_qty = COALESCE(pl.assembled_packed_qty, ad.assembled_packed_qty),
               assembly_date = COALESCE(pl.assembly_date, ad.assembly_date)
          FROM order_assembly_dispatch ad
         WHERE ad.order_id = pl.order_id;
        ALTER TABLE order_assembly_dispatch DROP COLUMN actual_pump_status;
        ALTER TABLE order_assembly_dispatch DROP COLUMN assembled_packed_qty;
        ALTER TABLE order_assembly_dispatch DROP COLUMN assembly_date;
    END IF;
END $$;

-- Final Dt. for Packing & Dispatch moves from Planning into Assembly &
-- Dispatch (filled by Assembly & Dispatch). Idempotent.
ALTER TABLE order_assembly_dispatch ADD COLUMN IF NOT EXISTS final_packing_dispatch_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_planning'
           AND column_name = 'final_packing_dispatch_date'
    ) THEN
        INSERT INTO order_assembly_dispatch (order_id)
            SELECT pl.order_id FROM order_planning pl
             WHERE pl.final_packing_dispatch_date IS NOT NULL
               AND NOT EXISTS (
                 SELECT 1 FROM order_assembly_dispatch ad WHERE ad.order_id = pl.order_id
               );
        UPDATE order_assembly_dispatch ad
           SET final_packing_dispatch_date = pl.final_packing_dispatch_date
          FROM order_planning pl
         WHERE pl.order_id = ad.order_id
           AND pl.final_packing_dispatch_date IS NOT NULL
           AND ad.final_packing_dispatch_date IS NULL;
        ALTER TABLE order_planning DROP COLUMN final_packing_dispatch_date;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- notifications
-- Event feed shown in the in-portal notification bell. Each row targets one
-- recipient role (a role may have several users; unread state is tracked
-- per-user via users.notifications_seen_at, below). Emitted when a triggering
-- event happens (payment terms filled, a target date set, a department
-- completing its work) — see lib/notifications.ts.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    recipient_role TEXT         NOT NULL,
    order_id       UUID         REFERENCES orders(id) ON DELETE CASCADE,
    type           TEXT         NOT NULL,   -- payment_terms | target_date | dept_complete
    message        TEXT         NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notifications_recipient_idx
    ON notifications(recipient_role, created_at DESC);

-- Per-user "last opened the bell" timestamp; unread = notifications newer than
-- this. Null means everything is unread.
ALTER TABLE users ADD COLUMN IF NOT EXISTS notifications_seen_at TIMESTAMPTZ;

-- QC Needed flag (orders.qc_required, Yes/No). 'No' means the QC department is
-- not involved for this order — it's hidden from the QC workspace and skipped
-- by QC reminders. Null/anything-but-'No' is treated as needed. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS qc_required TEXT;

-- ---------------------------------------------------------------------------
-- chat_messages
-- 1:1 direct messages. A conversation is just the pair of users — no separate
-- conversations table. Business rule (enforced in lib/chat.ts): every thread
-- pairs one central-side user (Admin / Central Visibility) with one department
-- user, so departments can only ever message Central Visibility.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_messages (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_id     UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id  UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body          TEXT         NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    read_at       TIMESTAMPTZ
);
-- Thread fetch: all messages between two users, oldest first.
CREATE INDEX IF NOT EXISTS chat_messages_pair_idx
    ON chat_messages(sender_id, recipient_id, created_at);
-- Unread badge: messages addressed to me that I haven't read.
CREATE INDEX IF NOT EXISTS chat_messages_inbox_idx
    ON chat_messages(recipient_id, read_at);

-- Sales Order Date, alongside the existing Sales Order Number (so_no). Part
-- of the "Purchase Order Details" group on the create form (SO No./Date next
-- to PO No./Date). Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS so_date DATE;

-- Currency for the Purchase/Sales Order Value (INR or USD), next to the
-- value itself rather than baked into the label text. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_currency TEXT;

-- Trim orders down to just Client + Purchase Order Details (+ system
-- columns). Everything else (EC fields, Item, QC Needed, Project, Payment
-- Terms, target dates) is dropped for now — the application code that reads
-- them (lib/reminders.ts, lib/alerts.ts, lib/notifications.ts, the order form
-- and summary) is intentionally left in place, since these columns are coming
-- back later. Until they're re-added, anything touching them will error.
ALTER TABLE orders DROP COLUMN IF EXISTS ec_no;
ALTER TABLE orders DROP COLUMN IF EXISTS ec_generated_date;
ALTER TABLE orders DROP COLUMN IF EXISTS ec_rcvd_operations_date;
ALTER TABLE orders DROP COLUMN IF EXISTS ec_sent_production_date;
ALTER TABLE orders DROP COLUMN IF EXISTS file_no;
ALTER TABLE orders DROP COLUMN IF EXISTS item;
ALTER TABLE orders DROP COLUMN IF EXISTS qc_required;
ALTER TABLE orders DROP COLUMN IF EXISTS model_no;
ALTER TABLE orders DROP COLUMN IF EXISTS pump_qty;
ALTER TABLE orders DROP COLUMN IF EXISTS pump_sno;
ALTER TABLE orders DROP COLUMN IF EXISTS orientation;
ALTER TABLE orders DROP COLUMN IF EXISTS liquid_application;
ALTER TABLE orders DROP COLUMN IF EXISTS version;
ALTER TABLE orders DROP COLUMN IF EXISTS project;
ALTER TABLE orders DROP COLUMN IF EXISTS payment_terms;
ALTER TABLE orders DROP COLUMN IF EXISTS master_reason_of_delay;
ALTER TABLE orders DROP COLUMN IF EXISTS dispatch_target_date;
ALTER TABLE orders DROP COLUMN IF EXISTS dispatch_target_revised_date;
ALTER TABLE orders DROP COLUMN IF EXISTS drg_target_date;

-- QC Req and Payment Terms return to the order (Central Visibility sets them
-- at intake, same as before they were trimmed above). LD / LD Date move from
-- Planning back onto the order too, so Central sets them at intake instead of
-- only later in Planning. Order Type (item) is NOT re-added here — it moves to
-- the per-EC order_items table in the v2 restructure below. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS qc_required TEXT;    -- QC Req (Yes/No)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_terms TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ld TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ld_date DATE;
-- ld and ld_date are moved independently: depending on migration history
-- order_planning may carry one without the other.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_planning' AND column_name = 'ld'
    ) THEN
        UPDATE orders o SET ld = COALESCE(o.ld, pl.ld)
          FROM order_planning pl WHERE pl.order_id = o.id;
        ALTER TABLE order_planning DROP COLUMN ld;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_planning' AND column_name = 'ld_date'
    ) THEN
        UPDATE orders o SET ld_date = COALESCE(o.ld_date, pl.ld_date)
          FROM order_planning pl WHERE pl.order_id = o.id;
        ALTER TABLE order_planning DROP COLUMN ld_date;
    END IF;
END $$;

-- ===========================================================================
-- v2 restructure: one SO (orders) → many ECs (order_items), each EC being one
-- pump or spare. Every department detail table moves from being keyed by the
-- SO (order_id) to being keyed by the EC (item_id) — so each pump flows through
-- Drawing → Purchase → QC → Planning → Dispatch on its own timeline. Client,
-- Purchase Order, Billing & Operations, Accounts, and the SO-level commercial
-- flags (Payment Terms / QC Req / LD) stay on the SO.
--
-- This is a destructive-by-consent migration: the per-department rows are
-- dropped and recreated keyed to order_items (the user approved a clean reset
-- of that data). It is guarded to run exactly once — the DROP only fires while
-- the detail tables still carry the old order_id column.
-- ===========================================================================

-- Per-EC line item (one pump or spare under an SO). Holds the intake attributes
-- and the per-EC target dates set by Central Visibility at Add-On time.
CREATE TABLE IF NOT EXISTS order_items (
    id                            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id                      UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    seq                           BIGINT GENERATED BY DEFAULT AS IDENTITY, -- display order
    ec_no                         TEXT,           -- EC No.
    ec_date                       DATE,           -- EC date
    item_type                     TEXT,           -- Pump / Spare / ROLB
    model_no                      TEXT,
    quantity                      INTEGER,
    orientation                   TEXT,
    pump_sno                      TEXT,           -- Pump Serial No.
    application                   TEXT,           -- Liquid / Application
    version                       TEXT,           -- Series Version
    boi                           TEXT,           -- BOI (Yes/No) intake flag
    dispatch_target_date          DATE,           -- Dispatch date
    dispatch_target_revised_date  DATE,           -- Revised dispatch date
    drg_target_date               DATE,           -- Target date for drawing
    qc_doc_target_date            DATE,           -- QC target date
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items (order_id);

DROP TRIGGER IF EXISTS order_items_set_updated_at ON order_items;
CREATE TRIGGER order_items_set_updated_at BEFORE UPDATE ON order_items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Drop the old SO-keyed detail tables once, so they can be recreated EC-keyed.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_drawing' AND column_name = 'order_id'
    ) THEN
        DROP TABLE IF EXISTS order_lots CASCADE;
        DROP TABLE IF EXISTS order_qc_documents CASCADE;
        DROP TABLE IF EXISTS order_qc_requirement_documents CASCADE;
        DROP TABLE IF EXISTS order_drawing CASCADE;
        DROP TABLE IF EXISTS order_purchase CASCADE;
        DROP TABLE IF EXISTS order_qc CASCADE;
        DROP TABLE IF EXISTS order_planning CASCADE;
        DROP TABLE IF EXISTS order_assembly_dispatch CASCADE;
    END IF;
END $$;

-- Drawing (per EC).
CREATE TABLE IF NOT EXISTS order_drawing (
    item_id                  UUID PRIMARY KEY REFERENCES order_items(id) ON DELETE CASCADE,
    drg_status               TEXT,
    drg_sent_to_client_date  DATE,
    drg_approval_date        DATE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Purchase / BOI (per EC). boi here drives the department's gear-box/motor
-- gating; order_items.boi is the intake flag captured on the Add-On form.
CREATE TABLE IF NOT EXISTS order_purchase (
    item_id               UUID PRIMARY KEY REFERENCES order_items(id) ON DELETE CASCADE,
    boi                   TEXT,
    gear_box              TEXT,
    gb_status             TEXT,
    motor                 TEXT,
    motor_status          TEXT,
    pending_parts         TEXT,
    boi_receipt_date      DATE,
    remarks               TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- QC (per EC). Target date now lives on order_items; QC fills the actual date.
CREATE TABLE IF NOT EXISTS order_qc (
    item_id                UUID PRIMARY KEY REFERENCES order_items(id) ON DELETE CASCADE,
    required_qc_documents  TEXT,
    qc_doc_actual_date     DATE,
    remarks                TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- QC document attachments (per EC, 1:many).
CREATE TABLE IF NOT EXISTS order_qc_documents (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id       UUID NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    file_name     TEXT NOT NULL,
    mime_type     TEXT,
    file_size     INT,
    file_data     BYTEA NOT NULL,
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_qc_documents_item_id_idx
    ON order_qc_documents(item_id);

-- QC requirement documents (per EC, 1:many).
CREATE TABLE IF NOT EXISTS order_qc_requirement_documents (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id       UUID NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    file_name     TEXT NOT NULL,
    mime_type     TEXT,
    file_size     INT,
    file_data     BYTEA NOT NULL,
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_qc_requirement_documents_item_id_idx
    ON order_qc_requirement_documents(item_id);

-- Planning (per EC).
CREATE TABLE IF NOT EXISTS order_planning (
    item_id                       UUID PRIMARY KEY REFERENCES order_items(id) ON DELETE CASCADE,
    purchase_target_date          DATE,
    planning_documents_required   TEXT,
    pump_readiness_remarks        TEXT,
    planning_readiness_date       DATE,
    planning_status               TEXT,
    actual_pump_status            TEXT,
    assembled_packed_qty          TEXT,
    assembly_date                 DATE,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Assembly & Dispatch (per EC).
CREATE TABLE IF NOT EXISTS order_assembly_dispatch (
    item_id                      UUID PRIMARY KEY REFERENCES order_items(id) ON DELETE CASCADE,
    dispatch_documents_required  TEXT,
    dispatch_team_target_date    DATE,
    final_packing_dispatch_date  DATE,
    actual_packing_date          DATE,
    delay_remarks                TEXT,
    dispatch_status              TEXT,
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Dispatch lots (per EC, 1:many).
CREATE TABLE IF NOT EXISTS order_lots (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id              UUID NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    lot_no               TEXT,
    lot_dispatch_date    DATE,
    packing_slip_remark  TEXT,
    invoice_date         DATE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_lots_item_id_idx ON order_lots (item_id);

-- updated_at triggers for the recreated 1:1 detail tables.
DROP TRIGGER IF EXISTS order_drawing_set_updated_at ON order_drawing;
CREATE TRIGGER order_drawing_set_updated_at BEFORE UPDATE ON order_drawing
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS order_purchase_set_updated_at ON order_purchase;
CREATE TRIGGER order_purchase_set_updated_at BEFORE UPDATE ON order_purchase
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS order_qc_set_updated_at ON order_qc;
CREATE TRIGGER order_qc_set_updated_at BEFORE UPDATE ON order_qc
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS order_planning_set_updated_at ON order_planning;
CREATE TRIGGER order_planning_set_updated_at BEFORE UPDATE ON order_planning
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS order_assembly_dispatch_set_updated_at ON order_assembly_dispatch;
CREATE TRIGGER order_assembly_dispatch_set_updated_at BEFORE UPDATE ON order_assembly_dispatch
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Order Type moves to the EC (order_items.item_type); remove it from the SO.
ALTER TABLE orders DROP COLUMN IF EXISTS item;

-- Notifications can target a specific EC (for per-EC target-date events); the
-- SO-level events (payment terms) keep using order_id only.
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS item_id UUID REFERENCES order_items(id) ON DELETE CASCADE;

-- Freight Terms & Packing Requirement move to the SO (orders) — Central sets
-- them in Order details; Billing sees them read-only. Billing also gains
-- Amount Received and a stored Balance of Payment (order value − amount
-- received, recomputed by the app on every billing/order-value save).
ALTER TABLE orders ADD COLUMN IF NOT EXISTS freight_terms TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS packing_requirement TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_billing' AND column_name = 'freight_terms'
    ) THEN
        UPDATE orders o
           SET freight_terms = COALESCE(o.freight_terms, b.freight_terms),
               packing_requirement = COALESCE(o.packing_requirement, b.packing_requirement)
          FROM order_billing b
         WHERE b.order_id = o.id;
        ALTER TABLE order_billing DROP COLUMN freight_terms;
        ALTER TABLE order_billing DROP COLUMN packing_requirement;
    END IF;
END $$;
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS amount_received NUMERIC(14,2);
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS balance_of_payment NUMERIC(14,2);

-- Order Type (Pump/Spare) is an SO-level classifier; every EC added under the
-- SO (Add-On) inherits it as its item_type.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_type TEXT;

-- BOI (Yes/No) moves to the SO's Purchase Order Details (Central sets it,
-- Purchase sees it read-only). Migrate any per-EC order_purchase.boi up to the
-- SO, then Purchase manages bought-out items as a per-EC list (order_boi_items)
-- and the old flat Purchase columns are dropped.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS boi TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_purchase' AND column_name = 'boi'
    ) THEN
        UPDATE orders o
           SET boi = COALESCE(o.boi, sub.boi)
          FROM (
            SELECT it.order_id, MAX(pu.boi) AS boi
              FROM order_purchase pu
              JOIN order_items it ON it.id = pu.item_id
             WHERE pu.boi IS NOT NULL
             GROUP BY it.order_id
          ) sub
         WHERE sub.order_id = o.id;
    END IF;
END $$;
-- Drop the old flat Purchase columns unconditionally (they're replaced by the
-- per-EC order_boi_items list) so none can linger or resurrect.
ALTER TABLE order_purchase DROP COLUMN IF EXISTS boi;
ALTER TABLE order_purchase DROP COLUMN IF EXISTS gear_box;
ALTER TABLE order_purchase DROP COLUMN IF EXISTS gb_status;
ALTER TABLE order_purchase DROP COLUMN IF EXISTS motor;
ALTER TABLE order_purchase DROP COLUMN IF EXISTS motor_status;
ALTER TABLE order_purchase DROP COLUMN IF EXISTS pending_parts;
ALTER TABLE order_purchase DROP COLUMN IF EXISTS boi_receipt_date;
ALTER TABLE order_purchase DROP COLUMN IF EXISTS remarks;

-- Per-EC bought-out items, managed by Purchase (Item + receipt date + remarks;
-- a free-text name when Item = Others).
CREATE TABLE IF NOT EXISTS order_boi_items (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id        UUID NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    boi_item       TEXT,   -- Gear Box / Motor / VFD / … / Others
    boi_item_other TEXT,   -- free text when boi_item = Others
    receipt_date   DATE,
    remarks        TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_boi_items_item_id_idx ON order_boi_items (item_id);

-- Amount Received & Balance of Payment move from Billing to Accounts (Accounts
-- fills them; Billing sees them read-only). Migrate any existing values across.
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS amount_received NUMERIC(14,2);
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS balance_of_payment NUMERIC(14,2);
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_billing' AND column_name = 'amount_received'
    ) THEN
        INSERT INTO order_accounts (order_id)
            SELECT b.order_id FROM order_billing b
             WHERE (b.amount_received IS NOT NULL OR b.balance_of_payment IS NOT NULL)
               AND NOT EXISTS (SELECT 1 FROM order_accounts a WHERE a.order_id = b.order_id);
        UPDATE order_accounts a
           SET amount_received = COALESCE(a.amount_received, b.amount_received),
               balance_of_payment = COALESCE(a.balance_of_payment, b.balance_of_payment)
          FROM order_billing b
         WHERE b.order_id = a.order_id;
        ALTER TABLE order_billing DROP COLUMN amount_received;
        ALTER TABLE order_billing DROP COLUMN balance_of_payment;
    END IF;
END $$;

-- Bill Type (Performa/Tax/Challan) on the SO (in Purchase Order Details); the
-- billing document fields shown depend on it.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS bill_type TEXT;

-- Billing document fields for Tax and Challan, alongside the existing PI
-- (Performa) fields. FR Reason applies to Challan.
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS tax_no TEXT;
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS tax_date DATE;
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS tax_value NUMERIC(14,2);
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS challan_no TEXT;
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS challan_date DATE;
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS challan_value NUMERIC(14,2);
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS fr_reason TEXT;

-- ===========================================================================
-- PIs become a 1:many list under an SO (order_billing_docs).
--
-- Bill Type is now Tax Invoice / Challan (Performa is gone). Billing adds one
-- or more PI rows per SO and fills the document fields (Tax Invoice → PI No. /
-- Date / Value; Challan → Challan No. / Date / Value + FR Reason). Accounts
-- then fills its payment details PER PI (status, confirmed date, amount
-- received), with Balance of Payment derived per PI.
--
-- The old flat 1:1 order_billing / order_accounts rows are superseded: their
-- document + payment columns move onto each PI row. order_accounts keeps only
-- the SO-level hold_reason escalation note.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS order_billing_docs (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id                UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    seq                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- Billing-owned document fields (which apply depends on the SO's bill_type).
    pi_no                   TEXT,
    pi_date                 DATE,
    pi_value                NUMERIC(14,2),
    challan_no              TEXT,
    challan_date            DATE,
    challan_value           NUMERIC(14,2),
    fr_reason               TEXT,
    -- Accounts-owned payment fields, per PI.
    payment_status          TEXT,
    payment_confirmed_date  DATE,
    amount_received         NUMERIC(14,2),
    balance_of_payment      NUMERIC(14,2),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_billing_docs_order_id_idx
    ON order_billing_docs (order_id);

DROP TRIGGER IF EXISTS order_billing_docs_set_updated_at ON order_billing_docs;
CREATE TRIGGER order_billing_docs_set_updated_at BEFORE UPDATE ON order_billing_docs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Migrate the existing single billing/accounts row into one PI row per SO.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_billing' AND column_name = 'pi_no'
    ) THEN
        INSERT INTO order_billing_docs (
            order_id, pi_no, pi_date, pi_value,
            challan_no, challan_date, challan_value, fr_reason,
            payment_status, payment_confirmed_date, amount_received, balance_of_payment
        )
        SELECT b.order_id, b.pi_no, b.pi_date, b.pi_value,
               b.challan_no, b.challan_date, b.challan_value, b.fr_reason,
               a.payment_status, a.payment_confirmed_date,
               a.amount_received, a.balance_of_payment
          FROM order_billing b
          LEFT JOIN order_accounts a ON a.order_id = b.order_id
         WHERE COALESCE(b.pi_no, b.challan_no, b.tax_no) IS NOT NULL
           AND NOT EXISTS (
             SELECT 1 FROM order_billing_docs d WHERE d.order_id = b.order_id
           );

        ALTER TABLE order_billing DROP COLUMN IF EXISTS pi_no;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS pi_date;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS pi_value;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS tax_no;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS tax_date;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS tax_value;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS challan_no;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS challan_date;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS challan_value;
        ALTER TABLE order_billing DROP COLUMN IF EXISTS fr_reason;

        ALTER TABLE order_accounts DROP COLUMN IF EXISTS payment_status;
        ALTER TABLE order_accounts DROP COLUMN IF EXISTS payment_confirmed_date;
        ALTER TABLE order_accounts DROP COLUMN IF EXISTS amount_received;
        ALTER TABLE order_accounts DROP COLUMN IF EXISTS balance_of_payment;
    END IF;
END $$;

-- Bill Type values: Performa is retired in favour of "Tax Invoice"; existing
-- 'Performa'/'Tax' rows map onto it.
UPDATE orders SET bill_type = 'Tax Invoice'
 WHERE bill_type IN ('Performa', 'Tax');

-- Clean up any lingering per-SO document/payment columns superseded by
-- order_billing_docs. These drops are safe: their values (if any) were carried
-- across in the DO block above. Idempotent thanks to IF EXISTS.
ALTER TABLE order_billing DROP COLUMN IF EXISTS tax_no;
ALTER TABLE order_billing DROP COLUMN IF EXISTS tax_date;
ALTER TABLE order_billing DROP COLUMN IF EXISTS tax_value;
ALTER TABLE order_billing DROP COLUMN IF EXISTS challan_no;
ALTER TABLE order_billing DROP COLUMN IF EXISTS challan_date;
ALTER TABLE order_billing DROP COLUMN IF EXISTS challan_value;
ALTER TABLE order_billing DROP COLUMN IF EXISTS fr_reason;
ALTER TABLE order_accounts DROP COLUMN IF EXISTS payment_status;
ALTER TABLE order_accounts DROP COLUMN IF EXISTS payment_confirmed_date;
ALTER TABLE order_accounts DROP COLUMN IF EXISTS amount_received;
ALTER TABLE order_accounts DROP COLUMN IF EXISTS balance_of_payment;

-- ===========================================================================
-- Reshape after PI list: Accounts reverts to a per-SO edit form (no per-PI
-- payment fields), Challan reverts to a single flat set on order_billing (no
-- add-on). order_billing_docs now carries only PI (Tax Invoice) documents.
-- ===========================================================================

-- Accounts payment fields return to order_accounts.
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS payment_status TEXT;
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS payment_confirmed_date DATE;
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS amount_received NUMERIC(14,2);
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS balance_of_payment NUMERIC(14,2);

-- Migrate any per-PI payment data back to per-SO (best-effort: earliest PI's
-- status/confirmed date, sum of amounts received).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'order_billing_docs' AND column_name = 'payment_status') THEN
        INSERT INTO order_accounts (order_id)
            SELECT DISTINCT d.order_id FROM order_billing_docs d
             WHERE (d.payment_status IS NOT NULL OR d.amount_received IS NOT NULL)
               AND NOT EXISTS (SELECT 1 FROM order_accounts a WHERE a.order_id = d.order_id);
        UPDATE order_accounts a SET
            payment_status = COALESCE(a.payment_status, (
              SELECT d.payment_status FROM order_billing_docs d
               WHERE d.order_id = a.order_id AND d.payment_status IS NOT NULL
               ORDER BY d.seq LIMIT 1)),
            payment_confirmed_date = COALESCE(a.payment_confirmed_date, (
              SELECT d.payment_confirmed_date FROM order_billing_docs d
               WHERE d.order_id = a.order_id AND d.payment_confirmed_date IS NOT NULL
               ORDER BY d.seq LIMIT 1)),
            amount_received = COALESCE(a.amount_received, (
              SELECT SUM(d.amount_received) FROM order_billing_docs d
               WHERE d.order_id = a.order_id));
    END IF;
END $$;

-- Drop payment fields from PI docs (accounts owns them now, per-SO).
ALTER TABLE order_billing_docs DROP COLUMN IF EXISTS payment_status;
ALTER TABLE order_billing_docs DROP COLUMN IF EXISTS payment_confirmed_date;
ALTER TABLE order_billing_docs DROP COLUMN IF EXISTS amount_received;
ALTER TABLE order_billing_docs DROP COLUMN IF EXISTS balance_of_payment;

-- Challan is single per SO again (no list). Restore its columns on order_billing.
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS challan_no TEXT;
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS challan_date DATE;
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS challan_value NUMERIC(14,2);
ALTER TABLE order_billing ADD COLUMN IF NOT EXISTS fr_reason TEXT;

-- Migrate any challan data from PI docs onto the SO's billing row, then delete
-- those PI rows (Challan doesn't use the PI list).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'order_billing_docs' AND column_name = 'challan_no') THEN
        INSERT INTO order_billing (order_id)
            SELECT DISTINCT d.order_id FROM order_billing_docs d
             JOIN orders o ON o.id = d.order_id
             WHERE o.bill_type = 'Challan' AND d.challan_no IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM order_billing b WHERE b.order_id = d.order_id);
        UPDATE order_billing b SET
            challan_no = COALESCE(b.challan_no, sub.challan_no),
            challan_date = COALESCE(b.challan_date, sub.challan_date),
            challan_value = COALESCE(b.challan_value, sub.challan_value),
            fr_reason = COALESCE(b.fr_reason, sub.fr_reason)
          FROM (
            SELECT DISTINCT ON (d.order_id) d.order_id, d.challan_no, d.challan_date,
                   d.challan_value, d.fr_reason
              FROM order_billing_docs d
              JOIN orders o ON o.id = d.order_id
             WHERE o.bill_type = 'Challan'
             ORDER BY d.order_id, d.seq
          ) sub
         WHERE b.order_id = sub.order_id;
        DELETE FROM order_billing_docs d USING orders o
         WHERE d.order_id = o.id AND o.bill_type = 'Challan';
    END IF;
END $$;

-- PI list is Tax-Invoice-only now.
ALTER TABLE order_billing_docs DROP COLUMN IF EXISTS challan_no;
ALTER TABLE order_billing_docs DROP COLUMN IF EXISTS challan_date;
ALTER TABLE order_billing_docs DROP COLUMN IF EXISTS challan_value;
ALTER TABLE order_billing_docs DROP COLUMN IF EXISTS fr_reason;
