-- ===========================================================================
-- ECtoDispatch — database schema
-- Target: Azure Database for PostgreSQL (Flexible Server)
-- Apply with:  npm run db:migrate
-- ===========================================================================

-- Note: gen_random_uuid() is built into PostgreSQL core (v13+), which Azure
-- Flexible Server runs, so no pgcrypto extension is required.

-- ---------------------------------------------------------------------------
-- users
-- Roles and access status match the login / "Request Access" signup flow.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name     TEXT         NOT NULL,
    email         TEXT         NOT NULL,
    password_hash TEXT         NOT NULL,
    role          TEXT         NOT NULL
                               CHECK (role IN ('admin', 'central_visibility', 'operations',
                                               'accounts', 'drawing', 'planning', 'purchase',
                                               'qc', 'dispatch')),
    status        TEXT         NOT NULL DEFAULT 'pending'
                               CHECK (status IN ('pending', 'approved', 'rejected', 'disabled')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Case-insensitive unique email (so Jane@x.com == jane@x.com).
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key
    ON users (lower(email));

-- Bring existing tables up to date with the CHECK constraints above.
-- Drop the old role check first, migrate the legacy 'assembly' role to the new
-- 'dispatch' role, then apply the expanded role set.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
UPDATE users SET role = 'dispatch' WHERE role = 'assembly';
ALTER TABLE users ADD  CONSTRAINT users_role_check
    CHECK (role IN ('admin', 'central_visibility', 'operations', 'accounts',
                    'drawing', 'planning', 'purchase', 'qc', 'dispatch'));
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_status_check;
ALTER TABLE users ADD  CONSTRAINT users_status_check
    CHECK (status IN ('pending', 'approved', 'rejected', 'disabled'));

-- Keep updated_at current on every UPDATE.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- audit_log — activity trail: who signed in, when, and what they did.
-- Actor identity is denormalized so entries survive user deletion and so
-- failed logins (no user row) can still be recorded.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES users(id) ON DELETE SET NULL,
    user_email  TEXT,
    user_role   TEXT,
    action      TEXT NOT NULL,   -- e.g. login, order.create, access.approve
    category    TEXT NOT NULL,   -- auth | activity | ownership
    target      TEXT,            -- what was affected (SO/EC, user email, …)
    details     TEXT,            -- human-readable summary
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_log_created_at_idx ON audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS audit_log_category_idx ON audit_log (category);
CREATE INDEX IF NOT EXISTS audit_log_user_idx ON audit_log (user_id);

-- ===========================================================================
-- Order-to-Dispatch master tracker (normalized)
--
-- A core `orders` row, one detail table per department (1:1 via order_id),
-- and child tables for pumps and lots (1:many). Every detail/child table
-- references orders(id) ON DELETE CASCADE. Column letters map to
-- assets/excelData.xlsx. Free-form/status fields are TEXT so messy imports
-- don't fail; clear dates/money/qty use proper types for sorting and totals.
-- ===========================================================================

-- Core identity — cols A–V (client/agent kept as plain text for now),
-- plus BH Project and BP Order Value.
CREATE TABLE IF NOT EXISTS orders (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sl_no                    BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- A  Sl. No.
    so_no                    TEXT,           -- B  SO NO.
    ec_no                    TEXT,           -- C  EC No.
    ec_generated_date        DATE,           -- D  EC Generated Date
    ec_rcvd_operations_date  DATE,           -- E  EC RCVD In OPERATIONS
    ec_sent_production_date  DATE,           -- F  EC sent date in Production
    file_no                  TEXT,           -- G  FILE NO.
    client_code              TEXT,           -- H  CLIENT CODE
    client_type              TEXT,           -- I  Client Type
    party                    TEXT,           -- J  Party
    nature_of_supply         TEXT,           -- K  Nature of Supply
    industry_type            TEXT,           -- L  INDUSTRY TYPE
    agent                    TEXT,           -- M  AGENT
    item                     TEXT,           -- N  Item
    po_no                    TEXT,           -- O  PO NO.
    customer_po_date         DATE,           -- P  Customer PO Date
    model_no                 TEXT,           -- Q  Model No.
    pump_qty                 INTEGER,        -- R  IF PUMP (QTY)
    pump_sno                 TEXT,           -- S  PUMP S.NO.
    orientation              TEXT,           -- T  ORIENTATION
    liquid_application       TEXT,           -- U  LIQUID/ APPLICATION
    version                  TEXT,           -- V  VERSION
    project                  TEXT,           -- BH Project
    payment_terms            TEXT,           -- W  Payment Terms (Central Visibility-owned)
    master_reason_of_delay   TEXT,           -- BK Master Reason of Delay (order-level)
    dispatch_target_date     DATE,           -- AU DISP. TARGET DT. (set after payment confirmation)
    dispatch_target_revised_date DATE,       -- AV Revise Disp. Target Dt (when LD)
    drg_target_date          DATE,           -- AG Target Dt. For Drg (Central Visibility-owned)
    order_value              NUMERIC(14,2),  -- BP Order Value
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS orders_so_no_idx ON orders (so_no);
CREATE INDEX IF NOT EXISTS orders_ec_no_idx ON orders (ec_no);

-- Billing & Operations / PI — cols W–AB.
CREATE TABLE IF NOT EXISTS order_billing (
    order_id             UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    freight_terms        TEXT,           -- X  Freight Terms
    packing_requirement  TEXT,           -- Y  Packing Requirement
    pi_no                TEXT,           -- Z  PI No.
    pi_date              DATE,           -- AA PI Date
    pi_value             NUMERIC(14,2),  -- AB PI Value
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Accounts — col AC + the Payment Confirmed gate.
-- payment_status carries the gate value (Pending / Received / Confirmed / Hold);
-- 'Hold' means not confirmed → escalated to Central Visibility.
CREATE TABLE IF NOT EXISTS order_accounts (
    order_id                UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    payment_status          TEXT,        -- AC Payment Status (gate value)
    payment_confirmed_date  DATE,        -- set when payment is Confirmed
    hold_reason             TEXT,        -- escalation note when on Hold
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add the gate columns to any pre-existing order_accounts table.
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS payment_confirmed_date DATE;
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS hold_reason TEXT;

-- Drawing — cols AD–AG ("in case of Pump").
CREATE TABLE IF NOT EXISTS order_drawing (
    order_id                 UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    drg_status               TEXT,       -- AD DRG. Status
    drg_sent_to_client_date  DATE,       -- AE DRG SENT TO CLIENT Dt.
    drg_approval_date        DATE,       -- AF DRG. Approval Date
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Purchase / BOI — cols AH–AO ("in case of Pump").
CREATE TABLE IF NOT EXISTS order_purchase (
    order_id              UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    boi                   TEXT,          -- AH BOI
    gear_box              TEXT,          -- AI Gear BOX
    gb_status             TEXT,          -- AJ GB STATUS
    motor                 TEXT,          -- AK Motor
    motor_status          TEXT,          -- AL MOTOR STATUS
    pending_parts         TEXT,          -- AM PENDING PARTS / BOI Others
    boi_receipt_date      DATE,          -- AN BOI DATE RECEIPT DATE
    remarks               TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE order_purchase ADD COLUMN IF NOT EXISTS remarks TEXT;

-- QC — cols AP–AS.
CREATE TABLE IF NOT EXISTS order_qc (
    order_id               UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    required_qc_documents  TEXT,         -- AP Required QC Documents
    qc_doc_target_date     DATE,         -- AQ Target Dt. For Doc. Submission
    qc_doc_actual_date     DATE,         -- AR Actual Dt. Of Doc. Submission
    remarks                TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE order_qc ADD COLUMN IF NOT EXISTS remarks TEXT;

-- QC document attachments (1:many). Filled by the QC role itself (unlike the
-- rest of the QC section, which Central Visibility fills); stored directly in
-- Postgres as bytea.
CREATE TABLE IF NOT EXISTS order_qc_documents (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id      UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    file_name     TEXT NOT NULL,
    mime_type     TEXT,
    file_size     INT,
    file_data     BYTEA NOT NULL,
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_qc_documents_order_id_idx
    ON order_qc_documents(order_id);

-- QC requirement documents (1:many). The reverse direction from
-- order_qc_documents: reference/requirement files Central Visibility uploads
-- for QC to work from (specs, standards, drawings), not QC's own output.
-- Central Visibility uploads/deletes; QC (+ Central) can view/download.
CREATE TABLE IF NOT EXISTS order_qc_requirement_documents (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id      UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    file_name     TEXT NOT NULL,
    mime_type     TEXT,
    file_size     INT,
    file_data     BYTEA NOT NULL,
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_qc_requirement_documents_order_id_idx
    ON order_qc_requirement_documents(order_id);

-- Planning — cols AT–AX, BB, BC, BG.
CREATE TABLE IF NOT EXISTS order_planning (
    order_id                      UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    ld                            TEXT,  -- LD (Yes/No), filled by Central Visibility
    ld_date                       DATE,  -- AT LD Date (filled by Central Visibility)
    purchase_target_date          DATE,  -- AO Target Dt. For Purchase (filled by Planning)
    planning_documents_required   TEXT,  -- AW Documents Required from Planning (Central Visibility)
    pump_readiness_remarks        TEXT,  -- AX Pump Readiness Remarks
    planning_readiness_date       DATE,  -- BB Readiness Dt. Rcvd from Planning
    final_packing_dispatch_date   DATE,  -- BC Final Dt. for Packing & Dispatch
    planning_status               TEXT,  -- BG PLANNING STATUS
    actual_pump_status            TEXT,  -- AY Actual PUMP STATUS (filled by Planning)
    assembled_packed_qty          TEXT,  -- AZ ASSEMBLED/ PACKED QTY (filled by Planning)
    assembly_date                 DATE,  -- BA Assembly date (filled by Planning)
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Assembly & Dispatch — cols BD–BF, BJ, BL.
CREATE TABLE IF NOT EXISTS order_assembly_dispatch (
    order_id                     UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    dispatch_documents_required  TEXT,  -- BD Documents Required by Assembly/Dispatch
    dispatch_team_target_date    DATE,  -- BE Target Date for Dispatch Team
    actual_packing_date          DATE,  -- BF ACTUAL Material Packing Date
    delay_remarks                TEXT,  -- BJ Remarks/Status/Reason of Delay
    dispatch_status              TEXT,  -- BL DISPATCH STATUS
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE order_assembly_dispatch DROP COLUMN IF EXISTS full_dispatch_date;

-- Payment Terms move to the order (filled by Central Visibility); Billing &
-- Operations and Accounts see it read-only. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_terms TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_billing'
           AND column_name = 'payment_terms'
    ) THEN
        UPDATE orders o
           SET payment_terms = COALESCE(o.payment_terms, b.payment_terms)
          FROM order_billing b
         WHERE b.order_id = o.id;
        ALTER TABLE order_billing DROP COLUMN payment_terms;
    END IF;
END $$;

-- Target Date for DRG moves to the order (filled by Central Visibility);
-- Drawing sees it read-only. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS drg_target_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_drawing' AND column_name = 'drg_target_date'
    ) THEN
        UPDATE orders o
           SET drg_target_date = COALESCE(o.drg_target_date, dr.drg_target_date)
          FROM order_drawing dr
         WHERE dr.order_id = o.id;
        ALTER TABLE order_drawing DROP COLUMN drg_target_date;
    END IF;
END $$;

-- Target Date for Purchase moves to Planning (filled by Planning); Purchase
-- sees it read-only. Idempotent.
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS purchase_target_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_purchase' AND column_name = 'purchase_target_date'
    ) THEN
        -- ensure a planning row exists for orders that carry a purchase target
        INSERT INTO order_planning (order_id)
            SELECT pu.order_id FROM order_purchase pu
             WHERE pu.purchase_target_date IS NOT NULL
               AND NOT EXISTS (
                 SELECT 1 FROM order_planning pl WHERE pl.order_id = pu.order_id
               );
        UPDATE order_planning pl
           SET purchase_target_date = pu.purchase_target_date
          FROM order_purchase pu
         WHERE pu.order_id = pl.order_id
           AND pu.purchase_target_date IS NOT NULL
           AND pl.purchase_target_date IS NULL;
        ALTER TABLE order_purchase DROP COLUMN purchase_target_date;
    END IF;
END $$;

-- LD is an order-level flag (orders.ld), not a QC attribute. Migrate any QC
-- ld_applicable values onto orders.ld, then drop the QC column. Idempotent.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_qc' AND column_name = 'ld_applicable'
    ) THEN
        UPDATE orders o
           SET ld = COALESCE(o.ld, qc.ld_applicable)
          FROM order_qc qc
         WHERE qc.order_id = o.id AND qc.ld_applicable IS NOT NULL;
        ALTER TABLE order_qc DROP COLUMN ld_applicable;
    END IF;
END $$;

-- LR no./date are no longer tracked.
ALTER TABLE order_lots DROP COLUMN IF EXISTS lr_no;
ALTER TABLE order_lots DROP COLUMN IF EXISTS lr_date;

-- Dispatch lots — cols BI, BM, BN, BO (1:many).
CREATE TABLE IF NOT EXISTS order_lots (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id             UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    lot_no               TEXT,          -- BM LOT NO.
    lot_dispatch_date    DATE,          -- BN Lot Wise Disp. Dt.
    packing_slip_remark  TEXT,          -- BI Lot wise Packing slip remark
    invoice_date         DATE,          -- BO Invoice Date
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_lots_order_id_idx ON order_lots (order_id);

-- updated_at triggers for the core + 1:1 detail tables.
DROP TRIGGER IF EXISTS orders_set_updated_at ON orders;
CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_billing_set_updated_at ON order_billing;
CREATE TRIGGER order_billing_set_updated_at BEFORE UPDATE ON order_billing
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_accounts_set_updated_at ON order_accounts;
CREATE TRIGGER order_accounts_set_updated_at BEFORE UPDATE ON order_accounts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_drawing_set_updated_at ON order_drawing;
CREATE TRIGGER order_drawing_set_updated_at BEFORE UPDATE ON order_drawing
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_purchase_set_updated_at ON order_purchase;
CREATE TRIGGER order_purchase_set_updated_at BEFORE UPDATE ON order_purchase
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_qc_set_updated_at ON order_qc;
CREATE TRIGGER order_qc_set_updated_at BEFORE UPDATE ON order_qc
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_planning_set_updated_at ON order_planning;
CREATE TRIGGER order_planning_set_updated_at BEFORE UPDATE ON order_planning
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_assembly_dispatch_set_updated_at ON order_assembly_dispatch;
CREATE TRIGGER order_assembly_dispatch_set_updated_at BEFORE UPDATE ON order_assembly_dispatch
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Move master_reason_of_delay from order_assembly_dispatch to orders (now an
-- order-level field captured at creation). Idempotent: copies any existing
-- values across, then drops the old column if it still exists.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS master_reason_of_delay TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_assembly_dispatch'
           AND column_name = 'master_reason_of_delay'
    ) THEN
        UPDATE orders o
           SET master_reason_of_delay = ad.master_reason_of_delay
          FROM order_assembly_dispatch ad
         WHERE ad.order_id = o.id
           AND ad.master_reason_of_delay IS NOT NULL
           AND o.master_reason_of_delay IS NULL;
        ALTER TABLE order_assembly_dispatch DROP COLUMN master_reason_of_delay;
    END IF;
END $$;

-- Move pump serial onto the order itself (one PUMP S.NO. per order) and drop
-- the former order_pumps child table. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pump_sno TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
         WHERE table_name = 'order_pumps'
    ) THEN
        UPDATE orders o
           SET pump_sno = p.pump_sno
          FROM (
            SELECT DISTINCT ON (order_id) order_id, pump_sno
              FROM order_pumps
             ORDER BY order_id, created_at
          ) p
         WHERE p.order_id = o.id
           AND o.pump_sno IS NULL
           AND p.pump_sno IS NOT NULL;
        DROP TABLE order_pumps;
    END IF;
END $$;

-- Dispatch target dates move to the order (filled by Central Visibility after
-- payment confirmation); Planning sees them read-only. Add an order-level LD
-- flag that gates the revised date. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ld TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS dispatch_target_date DATE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS dispatch_target_revised_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_planning'
           AND column_name = 'dispatch_target_date'
    ) THEN
        UPDATE orders o
           SET dispatch_target_date =
                 COALESCE(o.dispatch_target_date, pl.dispatch_target_date),
               dispatch_target_revised_date =
                 COALESCE(o.dispatch_target_revised_date, pl.dispatch_target_revised_date)
          FROM order_planning pl
         WHERE pl.order_id = o.id;
        ALTER TABLE order_planning DROP COLUMN dispatch_target_date;
        ALTER TABLE order_planning DROP COLUMN dispatch_target_revised_date;
    END IF;
END $$;

-- LD moves from orders into order_planning (filled by Central Visibility,
-- visible to Planning). Idempotent.
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS ld TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'orders' AND column_name = 'ld'
    ) THEN
        INSERT INTO order_planning (order_id)
            SELECT o.id FROM orders o
             WHERE o.ld IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM order_planning pl WHERE pl.order_id = o.id);
        UPDATE order_planning pl
           SET ld = o.ld
          FROM orders o
         WHERE o.id = pl.order_id AND o.ld IS NOT NULL AND pl.ld IS NULL;
        ALTER TABLE orders DROP COLUMN ld;
    END IF;
END $$;

-- Actual pump status / assembled qty / assembly date move from Assembly &
-- Dispatch into Planning (filled by Planning). Idempotent.
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS actual_pump_status TEXT;
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS assembled_packed_qty TEXT;
ALTER TABLE order_planning ADD COLUMN IF NOT EXISTS assembly_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_assembly_dispatch'
           AND column_name = 'actual_pump_status'
    ) THEN
        INSERT INTO order_planning (order_id)
            SELECT ad.order_id FROM order_assembly_dispatch ad
             WHERE (ad.actual_pump_status IS NOT NULL
                    OR ad.assembled_packed_qty IS NOT NULL
                    OR ad.assembly_date IS NOT NULL)
               AND NOT EXISTS (SELECT 1 FROM order_planning pl WHERE pl.order_id = ad.order_id);
        UPDATE order_planning pl
           SET actual_pump_status = COALESCE(pl.actual_pump_status, ad.actual_pump_status),
               assembled_packed_qty = COALESCE(pl.assembled_packed_qty, ad.assembled_packed_qty),
               assembly_date = COALESCE(pl.assembly_date, ad.assembly_date)
          FROM order_assembly_dispatch ad
         WHERE ad.order_id = pl.order_id;
        ALTER TABLE order_assembly_dispatch DROP COLUMN actual_pump_status;
        ALTER TABLE order_assembly_dispatch DROP COLUMN assembled_packed_qty;
        ALTER TABLE order_assembly_dispatch DROP COLUMN assembly_date;
    END IF;
END $$;

-- Final Dt. for Packing & Dispatch moves from Planning into Assembly &
-- Dispatch (filled by Assembly & Dispatch). Idempotent.
ALTER TABLE order_assembly_dispatch ADD COLUMN IF NOT EXISTS final_packing_dispatch_date DATE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_planning'
           AND column_name = 'final_packing_dispatch_date'
    ) THEN
        INSERT INTO order_assembly_dispatch (order_id)
            SELECT pl.order_id FROM order_planning pl
             WHERE pl.final_packing_dispatch_date IS NOT NULL
               AND NOT EXISTS (
                 SELECT 1 FROM order_assembly_dispatch ad WHERE ad.order_id = pl.order_id
               );
        UPDATE order_assembly_dispatch ad
           SET final_packing_dispatch_date = pl.final_packing_dispatch_date
          FROM order_planning pl
         WHERE pl.order_id = ad.order_id
           AND pl.final_packing_dispatch_date IS NOT NULL
           AND ad.final_packing_dispatch_date IS NULL;
        ALTER TABLE order_planning DROP COLUMN final_packing_dispatch_date;
    END IF;
END $$;
