-- ===========================================================================
-- ECtoDispatch — database schema
-- Target: Azure Database for PostgreSQL (Flexible Server)
-- Apply with:  npm run db:migrate
-- ===========================================================================

-- Note: gen_random_uuid() is built into PostgreSQL core (v13+), which Azure
-- Flexible Server runs, so no pgcrypto extension is required.

-- ---------------------------------------------------------------------------
-- users
-- Roles and access status match the login / "Request Access" signup flow.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name     TEXT         NOT NULL,
    email         TEXT         NOT NULL,
    password_hash TEXT         NOT NULL,
    role          TEXT         NOT NULL
                               CHECK (role IN ('admin', 'central_visibility', 'operations',
                                               'accounts', 'drawing', 'planning', 'purchase',
                                               'qc', 'dispatch')),
    status        TEXT         NOT NULL DEFAULT 'pending'
                               CHECK (status IN ('pending', 'approved', 'rejected', 'disabled')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Case-insensitive unique email (so Jane@x.com == jane@x.com).
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key
    ON users (lower(email));

-- Bring existing tables up to date with the CHECK constraints above.
-- Drop the old role check first, migrate the legacy 'assembly' role to the new
-- 'dispatch' role, then apply the expanded role set.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
UPDATE users SET role = 'dispatch' WHERE role = 'assembly';
ALTER TABLE users ADD  CONSTRAINT users_role_check
    CHECK (role IN ('admin', 'central_visibility', 'operations', 'accounts',
                    'drawing', 'planning', 'purchase', 'qc', 'dispatch'));
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_status_check;
ALTER TABLE users ADD  CONSTRAINT users_status_check
    CHECK (status IN ('pending', 'approved', 'rejected', 'disabled'));

-- Keep updated_at current on every UPDATE.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ===========================================================================
-- Order-to-Dispatch master tracker (normalized)
--
-- A core `orders` row, one detail table per department (1:1 via order_id),
-- and child tables for pumps and lots (1:many). Every detail/child table
-- references orders(id) ON DELETE CASCADE. Column letters map to
-- assets/excelData.xlsx. Free-form/status fields are TEXT so messy imports
-- don't fail; clear dates/money/qty use proper types for sorting and totals.
-- ===========================================================================

-- Core identity — cols A–V (client/agent kept as plain text for now),
-- plus BH Project and BP Order Value.
CREATE TABLE IF NOT EXISTS orders (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sl_no                    BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- A  Sl. No.
    so_no                    TEXT,           -- B  SO NO.
    ec_no                    TEXT,           -- C  EC No.
    ec_generated_date        DATE,           -- D  EC Generated Date
    ec_rcvd_operations_date  DATE,           -- E  EC RCVD In OPERATIONS
    ec_sent_production_date  DATE,           -- F  EC sent date in Production
    file_no                  TEXT,           -- G  FILE NO.
    client_code              TEXT,           -- H  CLIENT CODE
    client_type              TEXT,           -- I  Client Type
    party                    TEXT,           -- J  Party
    nature_of_supply         TEXT,           -- K  Nature of Supply
    industry_type            TEXT,           -- L  INDUSTRY TYPE
    agent                    TEXT,           -- M  AGENT
    item                     TEXT,           -- N  Item
    po_no                    TEXT,           -- O  PO NO.
    customer_po_date         DATE,           -- P  Customer PO Date
    model_no                 TEXT,           -- Q  Model No.
    pump_qty                 INTEGER,        -- R  IF PUMP (QTY)
    pump_sno                 TEXT,           -- S  PUMP S.NO.
    orientation              TEXT,           -- T  ORIENTATION
    liquid_application       TEXT,           -- U  LIQUID/ APPLICATION
    version                  TEXT,           -- V  VERSION
    project                  TEXT,           -- BH Project
    master_reason_of_delay   TEXT,           -- BK Master Reason of Delay (order-level)
    order_value              NUMERIC(14,2),  -- BP Order Value
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS orders_so_no_idx ON orders (so_no);
CREATE INDEX IF NOT EXISTS orders_ec_no_idx ON orders (ec_no);

-- Billing & Operations / PI — cols W–AB.
CREATE TABLE IF NOT EXISTS order_billing (
    order_id             UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    payment_terms        TEXT,           -- W  Payment Terms
    freight_terms        TEXT,           -- X  Freight Terms
    packing_requirement  TEXT,           -- Y  Packing Requirement
    pi_no                TEXT,           -- Z  PI No.
    pi_date              DATE,           -- AA PI Date
    pi_value             NUMERIC(14,2),  -- AB PI Value
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Accounts — col AC + the Payment Confirmed gate.
-- payment_status carries the gate value (Pending / Received / Confirmed / Hold);
-- 'Hold' means not confirmed → escalated to Central Visibility.
CREATE TABLE IF NOT EXISTS order_accounts (
    order_id                UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    payment_status          TEXT,        -- AC Payment Status (gate value)
    payment_confirmed_date  DATE,        -- set when payment is Confirmed
    hold_reason             TEXT,        -- escalation note when on Hold
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add the gate columns to any pre-existing order_accounts table.
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS payment_confirmed_date DATE;
ALTER TABLE order_accounts ADD COLUMN IF NOT EXISTS hold_reason TEXT;

-- Drawing — cols AD–AG ("in case of Pump").
CREATE TABLE IF NOT EXISTS order_drawing (
    order_id                 UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    drg_status               TEXT,       -- AD DRG. Status
    drg_sent_to_client_date  DATE,       -- AE DRG SENT TO CLIENT Dt.
    drg_approval_date        DATE,       -- AF DRG. Approval Date
    drg_target_date          DATE,       -- AG Target Dt. For Drg
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Purchase / BOI — cols AH–AO ("in case of Pump").
CREATE TABLE IF NOT EXISTS order_purchase (
    order_id              UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    boi                   TEXT,          -- AH BOI
    gear_box              TEXT,          -- AI Gear BOX
    gb_status             TEXT,          -- AJ GB STATUS
    motor                 TEXT,          -- AK Motor
    motor_status          TEXT,          -- AL MOTOR STATUS
    pending_parts         TEXT,          -- AM PENDING PARTS / BOI Others
    boi_receipt_date      DATE,          -- AN BOI DATE RECEIPT DATE
    purchase_target_date  DATE,          -- AO Target Dt. For Purchase
    remarks               TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE order_purchase ADD COLUMN IF NOT EXISTS remarks TEXT;

-- QC — cols AP–AS.
CREATE TABLE IF NOT EXISTS order_qc (
    order_id               UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    required_qc_documents  TEXT,         -- AP Required QC Documents
    qc_doc_target_date     DATE,         -- AQ Target Dt. For Doc. Submission
    qc_doc_actual_date     DATE,         -- AR Actual Dt. Of Doc. Submission
    ld_applicable          TEXT,         -- AS LD (Yes)
    remarks                TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE order_qc ADD COLUMN IF NOT EXISTS remarks TEXT;

-- Planning — cols AT–AX, BB, BC, BG.
CREATE TABLE IF NOT EXISTS order_planning (
    order_id                      UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    ld_date                       DATE,  -- AT LD Date
    dispatch_target_date          DATE,  -- AU DISP. TARGET DT.
    dispatch_target_revised_date  DATE,  -- AV Revise Disp. Target Dt
    planning_documents_required   TEXT,  -- AW Documents Required from Planning
    pump_readiness_remarks        TEXT,  -- AX Pump Readiness Remarks
    planning_readiness_date       DATE,  -- BB Readiness Dt. Rcvd from Planning
    final_packing_dispatch_date   DATE,  -- BC Final Dt. for Packing & Dispatch
    planning_status               TEXT,  -- BG PLANNING STATUS
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Assembly & Dispatch — cols AY–BA, BD–BF, BJ, BK, BL.
CREATE TABLE IF NOT EXISTS order_assembly_dispatch (
    order_id                     UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    actual_pump_status           TEXT,  -- AY Actual PUMP STATUS
    assembled_packed_qty         TEXT,  -- AZ ASSEMBLED/ PACKED QTY
    assembly_date                DATE,  -- BA Assembly date
    dispatch_documents_required  TEXT,  -- BD Documents Required by Assembly/Dispatch
    dispatch_team_target_date    DATE,  -- BE Target Date for Dispatch Team
    actual_packing_date          DATE,  -- BF ACTUAL Material Packing Date
    delay_remarks                TEXT,  -- BJ Remarks/Status/Reason of Delay
    dispatch_status              TEXT,  -- BL DISPATCH STATUS
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Dispatch lots — cols BI, BM, BN, BO (1:many).
CREATE TABLE IF NOT EXISTS order_lots (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id             UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    lot_no               TEXT,          -- BM LOT NO.
    lot_dispatch_date    DATE,          -- BN Lot Wise Disp. Dt.
    lr_no                TEXT,          -- Lorry Receipt no. (dispatch completed)
    lr_date              DATE,          -- Lorry Receipt date
    packing_slip_remark  TEXT,          -- BI Lot wise Packing slip remark
    invoice_date         DATE,          -- BO Invoice Date
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_lots_order_id_idx ON order_lots (order_id);

-- LR columns for pre-existing order_lots tables.
ALTER TABLE order_lots ADD COLUMN IF NOT EXISTS lr_no TEXT;
ALTER TABLE order_lots ADD COLUMN IF NOT EXISTS lr_date DATE;

-- updated_at triggers for the core + 1:1 detail tables.
DROP TRIGGER IF EXISTS orders_set_updated_at ON orders;
CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_billing_set_updated_at ON order_billing;
CREATE TRIGGER order_billing_set_updated_at BEFORE UPDATE ON order_billing
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_accounts_set_updated_at ON order_accounts;
CREATE TRIGGER order_accounts_set_updated_at BEFORE UPDATE ON order_accounts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_drawing_set_updated_at ON order_drawing;
CREATE TRIGGER order_drawing_set_updated_at BEFORE UPDATE ON order_drawing
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_purchase_set_updated_at ON order_purchase;
CREATE TRIGGER order_purchase_set_updated_at BEFORE UPDATE ON order_purchase
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_qc_set_updated_at ON order_qc;
CREATE TRIGGER order_qc_set_updated_at BEFORE UPDATE ON order_qc
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_planning_set_updated_at ON order_planning;
CREATE TRIGGER order_planning_set_updated_at BEFORE UPDATE ON order_planning
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS order_assembly_dispatch_set_updated_at ON order_assembly_dispatch;
CREATE TRIGGER order_assembly_dispatch_set_updated_at BEFORE UPDATE ON order_assembly_dispatch
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Move master_reason_of_delay from order_assembly_dispatch to orders (now an
-- order-level field captured at creation). Idempotent: copies any existing
-- values across, then drops the old column if it still exists.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS master_reason_of_delay TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'order_assembly_dispatch'
           AND column_name = 'master_reason_of_delay'
    ) THEN
        UPDATE orders o
           SET master_reason_of_delay = ad.master_reason_of_delay
          FROM order_assembly_dispatch ad
         WHERE ad.order_id = o.id
           AND ad.master_reason_of_delay IS NOT NULL
           AND o.master_reason_of_delay IS NULL;
        ALTER TABLE order_assembly_dispatch DROP COLUMN master_reason_of_delay;
    END IF;
END $$;

-- Move pump serial onto the order itself (one PUMP S.NO. per order) and drop
-- the former order_pumps child table. Idempotent.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pump_sno TEXT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
         WHERE table_name = 'order_pumps'
    ) THEN
        UPDATE orders o
           SET pump_sno = p.pump_sno
          FROM (
            SELECT DISTINCT ON (order_id) order_id, pump_sno
              FROM order_pumps
             ORDER BY order_id, created_at
          ) p
         WHERE p.order_id = o.id
           AND o.pump_sno IS NULL
           AND p.pump_sno IS NOT NULL;
        DROP TABLE order_pumps;
    END IF;
END $$;
